### ISSUE TITLE
TypeError: undefined is not a constructor (evaluating 'allKeys[i].match(/^[0-9]+$/)')

### ISSUE THREAD

**Issue by jonashartwig** [jasmine/jasmine#1321]
Hi, this issue seems to have resurfaced. Works with 2.5.2 but not with 2.6.0.

 - 2.6.0
 - node with karma

    it("should calculate correct when xAxisLabels length less than 8", () =>
        expect(buildDefaultDataZoom({}, []))
        .toEqual(
            [{
                startValue: 0,
                endValue: 0
            }, {
                type: "inside"
            }]
        )
    )

regards

**Comment by EstartuPrime** [comment]
Hello, 
i have the same here. My nightly build failed with jasmine 2.6.0 worked with jasmine 2.5.3 and jasmine-core 2.5.2 before.

`PhantomJS 2.1.1 (Linux 0.0.0) Broadcast service  Function register() should not add an listener to the same event from the same module FAILED
	TypeError: undefined is not a function (evaluating 'allKeys[i].match(/^[0-9]+$/)') in node_modules/jasmine-core/lib/jasmine-core/jasmine.js (line 2576)
	spec/blocks/broadcast/broadcast.service.spec.js:63:66
`

All test's fail with a .toEqual() call.

Best regards
Alex

**Comment by DamienCassou** [comment]
This looks like this: http://www.mzan.com/article/39288777-karma-jasmine-phantomjs-undefined-is-not-a-constructor.shtml
