### ISSUE TITLE
Creating spy constructors/prototypes no longer works with 3.6.0

### ISSUE THREAD

**Issue by dsommerich** [jasmine/jasmine#1841]
The following example works with 3.5.0 but not with 3.6.0:

```js
it('bla', () => {
    const MockConstructor = jasmine.createSpy('MockConstructor');
    MockConstructor.prototype = jasmine.createSpyObj('MockConstructor.prototype', ['foo']);

    const mock = new MockConstructor();
    mock.foo();
});
```

## Expected Behavior

The code runs successfully and calls `MockConstructor.prototype.foo`.

## Current Behavior

A type error is thrown at `mock.foo()`:

```
Failures:
1) bla
  Message:
    TypeError: mock.foo is not a function
  Stack:
    TypeError: mock.foo is not a function
        at UserContext.<anonymous> (/home/dsommerich/Documents/id-public-api-facade/test/unit/test.spec.js:8:10)
        at <Jasmine>
        at processImmediate (internal/timers.js:458:21)
```

## Suite that reproduces the behavior (for bugs)

See above :slightly_smiling_face:.

## Context

We have a few tests that rely on this, since they test mixin classes. We can't really test these mixins well without mocking the base class.

## Your Environment

* Version used: 3.5.0, 3.6.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node v14.6.0
* Operating System and version (desktop or mobile): Linux
* Link to your project: N/A

**Comment by slackersoft** [comment]
It looks like the fix for spies correctly invoking constructor functions (#1782) bit us in this slightly different use case. I know it's not super awesome, but I was able to get this version of the test to work with Jasmine 3.6:

```javascript
it('with call', function() {
  function FakeConstructor() {}
  const MockConstructor = jasmine.createSpy('MockConstructor').and.callFake(FakeConstructor);
  FakeConstructor.prototype = jasmine.createSpyObj('MockConstructor.prototype', ['foo']);

  const mock = new MockConstructor();
  mock.foo();
});
```

The root cause here is that in order to pass all of the arguments along to the _real_ function (when using `.and.callThrough`), we need to bind the current arguments into a new function so it can be invoked with the `new` operator (you can't use `new` with `.call()`) and in doing this we lose any `prototype` that was on the spy itself. However, Jasmine will now correctly keep any prototype that exists on an underlying function (`callFake` or `callThrough`).

I'd also be happy to review a pull request to add back in the functionality that you were relying on, as long as we can get it without breaking the newer stuff.

Hope this helps. Thanks for using Jasmine!

**Comment by dsommerich** [comment]
Thanks for that workaround, it does solve this simple case I gave, but unfortunately my actual test doesn't work with this workaround.

This is a better example of my actual test case:

```js
    const MockParent = jasmine.createSpy('MockParent');
    MockParent.prototype = {foo: jasmine.createSpy('MockParent.foo')};

    class Child extends MockParent {
        foo(arg) {
            super.foo(arg + '123'); // Does something which arg before passing to parent
        }
    }

    const child = new Child('constructor arg');
    expect(MockParent).toHaveBeenCalledWith('constructor arg');

    child.foo('foo arg');
    expect(MockParent.prototype.foo).toHaveBeenCalledWith('foo arg123');
```

Updating the above to use your suggested workaround:

```js
    function FakeParent() {}
    FakeParent.prototype = {foo: jasmine.createSpy('MockParent.foo')};
    const MockParent = jasmine.createSpy('MockParent').and.callFake(FakeParent);

    class Child extends MockParent {
        foo(arg) {
            super.foo(arg + '123'); // Does something which arg before passing to parent
        }
    }

    const child = new Child('constructor arg');
    expect(MockParent).toHaveBeenCalledWith('constructor arg'); // works

    child.foo('foo arg');
    expect(FakeParent.prototype.foo).toHaveBeenCalledWith('foo arg123'); // fails here, called with 'foo arg' instead of 'foo arg123'

    expect(child).toBeInstanceOf(Child); // this fails too
```

This gets the parent class's prototype working properly, but because of how `callFake` is implemented ([it calls `new` on the target directly and returns the result](https://github.com/jasmine/jasmine/pull/1782/files#diff-9dca93587adbefb5497a916a39adf8f8R105)), the child class is completely ignored (since the returned object overrides the automatically created `this` object when calling `new`).

I was able to implement a workaround, which requires wrapping the spies in a regular class instead of using a spy as a class directly:

```js
    const mockConstructor = jasmine.createSpy('mockConstructor');
    const mockFoo = jasmine.createSpy('mockFoo');

    class MockParent {
        constructor(...args) {
            mockConstructor.apply(this, args);
        }

        foo(...args) {
            mockFoo.apply(this, args);
        }
    }

    class Child extends MockParent {
        foo(arg) {
            super.foo(arg + '123'); // Does something which arg before passing to parent
        }
    }

    const child = new Child('constructor arg');
    expect(mockConstructor).toHaveBeenCalledWith('constructor arg');

    child.foo('foo arg');
    expect(mockFoo).toHaveBeenCalledWith('foo arg123');

    expect(child).toBeInstanceOf(Child);
```

It would be nice if `callFake` worked with `extends`, but after looking at the code I don't really see how it could be done easily.

But my problem is solved for now. Thanks for the help.

**Comment by HolgerJeromin** [comment]
I had a similar problem with spy of `DateTimeFormat`. Worked with 3.5.0 not anymore with 3.6.0
We removed support for IE11 and early edge support in our software so I was free to remove this part of the tests after trying to support jasmine 3.6.0.
But perhaps someone will need this.

```ts
// Killing time zone support to align modern browsers to IE11 and early edge support
const originalDateTimeFormat = Intl.DateTimeFormat;
spyOn(Intl, 'DateTimeFormat').and.callFake(((locales?: string | string[], options?: Intl.DateTimeFormatOptions) => {
	if (!options) {
		// no options is OK
	} else if (options.timeZone === undefined) {
		// browser timeZone is OK
	} else if (options.timeZone && options.timeZone.toLowerCase() === 'utc') {
		// utc is OK
	} else {
		throw new RangeError('We want to fake unsupported time zone');
	}
	return new originalDateTimeFormat(locales, options);
}) as any);
```
